application: potatoblogging
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: django
  version: "1.5"
- name: MySQLdb
  version: "latest"

builtins:
- django_wsgi: on

handlers:
- url: /.*
  script: main.py
- url: /static
  static_dir: /blog/static
  expiration: '0'
